dist: bionic
language: cpp
os:
  - linux
  - osx

matrix:
  include:
    - os: linux
    - os: osx
      osx_image: xcode7.2
    - os: osx
      osx_image: xcode8.1
    - compiler: gcc
      env: COMPILER=g++
    - compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - libboost-test-dev
            - g++-5
      env: COMPILER=g++-5
    - compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - libboost-test-dev
            - g++-6
      env: COMPILER=g++-6
    - compiler: clang
      env: COMPILER=clang++
addons:
  apt:
    packages:
      - libboost-test-dev
script:
  - ./autogen.sh
  - make distcheck
